"""add_account_lockout_fields

Revision ID: 9e765fbd5e8e
Revises: 2f006585ba26
Create Date: 2025-12-17 12:14:10.427944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e765fbd5e8e'
down_revision: Union[str, None] = '2f006585ba26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.BigInteger(), nullable=False, comment='Count of consecutive failed login attempts'))
    op.add_column('users', sa.Column('account_locked_until', sa.BigInteger(), nullable=True, comment='Unix timestamp (ms) until which account is locked'))
    op.add_column('users', sa.Column('last_failed_login', sa.BigInteger(), nullable=True, comment='Timestamp of last failed login attempt (ms)'))
    op.add_column('users', sa.Column('last_successful_login', sa.BigInteger(), nullable=True, comment='Timestamp of last successful login (ms)'))
    op.alter_column('users', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='User settings JSON: theme, session config, view preferences',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='User settings JSON: theme, session config, view preferences',
               existing_nullable=False)
    op.drop_column('users', 'last_successful_login')
    op.drop_column('users', 'last_failed_login')
    op.drop_column('users', 'account_locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
